package generator

import (
	"fmt"
	"io/ioutil"
	"log"
)

func Run(input Root) {
	b := []byte(fmt.Sprintf(`// Code generated by Photon Go. DO NOT EDIT.
// The input schema was taken from %s
package main`, input.SchemaPath))
	err := ioutil.WriteFile(input.Generator.Output, b, 0644)
	if err != nil {
		log.Fatalf("could not write file %s", err)
	}
}
