name-template: v$NEXT_MINOR_VERSION
sort-direction: ascending
exclude-labels:
  - 'skip-changelog'
  - 'dependencies'
  - 'ci'
  - 'chore'
exclude-contributors:
  - 'dependabot[bot]'
autolabeler:
  - label: 'ci'
    branch:
      - '/ci\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
template: |
  # v$NEXT_MINOR_VERSION

  TODO: description

  ## Major changes

  TODO: list major changes

  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
