name: e2e test all
on: pull_request
jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            go:
              - '.github/workflows/**/*.yml'
              - '**/*.go'
              - '**/*.gotpl'
              - '**/*.mod'
              - '**/*.sum'
              - '**/*.work'

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache
          restore-keys: ${{ runner.os }}-go-
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: deps
        run: go mod download

      - name: generate
        if: steps.changes.outputs.go == 'true'
        run: |
          cd test/e2e/
          go generate -tags e2e ./...
        # env:
        #   DATA_PROXY_DATABASE_URL: ${{ secrets.DATA_PROXY_DATABASE_URL }}

      - name: test
        if: steps.changes.outputs.go == 'true'
        run: |
          cd test/e2e/
          go test ./... -run '^TestE2E.*$' -tags e2e -race -v
        env:
          # DATA_PROXY_DATABASE_URL: ${{ secrets.DATA_PROXY_DATABASE_URL }}
          PRISMA_CLIENT_GO_LOG: info
